name: starter_app
description: Flutter starter app

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  intl: ^0.18.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.2.0
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  supabase_flutter: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.5
  stacked_generator: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
